# This is your custom image name and metadata
name: evilpandas-os
description: My custom Bluefin image with DisplayLink and kernel dev tools.

# This IS Bluefin. Bluefin is part of the ublue-os organization.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: akmods
    install:
      - evdi
    repos:
      - https://negativo17.org/repos/fedora-multimedia.repo

  - type: rpm-ostree
    repos:
      - https://negativo17.org/repos/fedora-multimedia.repo
    install:
      - displaylink
      - libevdi     # The library required by DisplayLink
      - kernel-devel # Required for building the module

  - type: script
    scripts:
      - displaylink-fix.sh
