# This is your custom image name and metadata
name: evilpandas-os
description: My custom Bluefin image with DisplayLink and kernel dev tools.

# This IS Bluefin. Bluefin is part of the ublue-os organization.
# - bluefin-dx: Standard developer image (Intel/AMD)
# - bluefin-dx-nvidia: If you have an Nvidia GPU
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://negativo17.org/repos/fedora-multimedia.repo
    install:
      - displaylink
      - evdi
      - akmod-evdi
      - kernel-devel # Required for building the module

  - type: script
    scripts:
      - displaylink-fix.sh
