# This is your custom image name and metadata
name: evilpandas-os
description: My custom Bluefin image with DisplayLink and kernel dev tools.

# This IS Bluefin. Bluefin is part of the ublue-os organization.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://negativo17.org/repos/fedora-multimedia.repo
    install:
      - kernel-devel
      - libevdi
      - displaylink

  - type: akmods
    install:
      - evdi

  - type: script
    scripts:
      - displaylink-fix.sh
