# This is your custom image name and metadata
name: evilpandas-os
description: My custom Bluefin image with DisplayLink and kernel dev tools.

# This IS Bluefin. Bluefin is part of the ublue-os organization.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  # We consolidate everything into a containerfile module to handle the 
  # complex dependency dance and repo requirements for DisplayLink.
  - type: containerfile
    snippets:
      - |
        # 1. Add the Negativo17 repository
        RUN curl -Lo /etc/yum.repos.d/fedora-multimedia.repo https://negativo17.org/repos/fedora-multimedia.repo
        
        # 2. Install kernel headers and build tools needed for the driver
        RUN rpm-ostree install kernel-devel kernel-headers akmods
        
        # 3. Install libevdi first (this should not pull in akmod-evdi)
        RUN rpm-ostree install libevdi
        
        # 4. Install displaylink. akmod-evdi will be pulled in as a dependency.
        # The akmod-evdi package's post-install scriptlet will fail because it tries
        # to build as root. We'll work around this by installing akmod-evdi manually
        # without running its scriptlets, then installing displaylink.
        RUN dnf download akmod-evdi -y && \
            rpm -Uvh --noscripts akmod-evdi*.rpm && \
            rm -f akmod-evdi*.rpm || true
        
        # 5. Now install displaylink (akmod-evdi is already installed, so it won't try to build)
        RUN rpm-ostree install displaylink
        
        # 6. Manually trigger the akmod build for evdi using the akmods user.
        # This ensures evdi is built correctly since we installed akmod-evdi without scriptlets.
        RUN su -s /bin/bash akmods -c "akmods --force --kernels $(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -n 1) --akmod evdi" || \
            akmods --force --kernels $(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -n 1) --akmod evdi

  # Finally, our tuning script to enable the service and set config
  - type: script
    scripts:
      - displaylink-fix.sh
