# This is your custom image name and metadata
name: evilpandas-os
description: My custom Bluefin image with DisplayLink and kernel dev tools.

# This IS Bluefin. Bluefin is part of the ublue-os organization.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  # We consolidate everything into a containerfile module to handle the 
  # complex dependency dance and repo requirements for DisplayLink.
  - type: containerfile
    snippets:
      - |
        # 1. Add the Negativo17 repository
        RUN curl -Lo /etc/yum.repos.d/fedora-multimedia.repo https://negativo17.org/repos/fedora-multimedia.repo
        
        # 2. Install kernel headers and build tools needed for the driver
        RUN rpm-ostree install kernel-devel kernel-headers akmods
        
        # 3. Install the DisplayLink components while ignoring weak dependencies.
        # This prevents the failing 'akmod-evdi' from being pulled in automatically.
        RUN rpm-ostree install --advisory=fedora-multimedia \
            libevdi \
            displaylink \
            --setopt=install_weak_deps=False \
            --assume-yes
        
        # 4. Manually trigger the akmod build for evdi using the correct parameters
        # for a containerized build environment.
        RUN akmods --force --kernels $(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -n 1) --akmod evdi

  # Finally, our tuning script to enable the service and set config
  - type: script
    scripts:
      - displaylink-fix.sh
