# This is your custom image name and metadata
name: evilpandas-os
description: My custom Bluefin image with DisplayLink and kernel dev tools.

# This IS Bluefin. Bluefin is part of the ublue-os organization.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  # First, we build the kernel module safely using the dedicated akmods module
  - type: akmods
    install:
      - evdi

  # Second, we use a raw Containerfile snippet to install displaylink while 
  # ignoring the problematic akmod-evdi dependency that fails in containers.
  - type: containerfile
    snippets:
      - |
        RUN curl -Lo /etc/yum.repos.d/fedora-multimedia.repo https://negativo17.org/repos/fedora-multimedia.repo && \
            rpm-ostree install --advisory=fedora-multimedia \
            kernel-devel \
            libevdi \
            displaylink \
            --setopt=install_weak_deps=False \
            --assume-yes

  # Finally, our tuning script
  - type: script
    scripts:
      - displaylink-fix.sh
