# This is your custom image name and metadata
name: evilpandas-os
description: My custom Bluefin image with DisplayLink and kernel dev tools.

# This IS Bluefin. Bluefin is part of the ublue-os organization.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  # We consolidate everything into a containerfile module to handle the 
  # complex dependency dance and repo requirements for DisplayLink.
  - type: containerfile
    snippets:
      - |
        # 1. Add the Negativo17 repository
        RUN curl -Lo /etc/yum.repos.d/fedora-multimedia.repo https://negativo17.org/repos/fedora-multimedia.repo
        
        # 2. Install kernel headers and build tools needed for the driver
        RUN rpm-ostree install kernel-devel kernel-headers akmods
        
        # 3. Install libevdi first (this should not pull in akmod-evdi)
        RUN rpm-ostree install libevdi
        
        # 4. Download all DisplayLink-related packages with dependencies, then install
        # them manually with --noscripts to skip the akmod-evdi post-install scriptlet
        # that tries to build as root. We'll build the kernel module manually in step 6.
        RUN dnf download --resolve displaylink akmod-evdi -y
        
        # 5. Install all downloaded packages without running scriptlets.
        # This prevents akmod-evdi from trying to build as root during installation.
        RUN rpm -Uvh --noscripts *.rpm && rm -f *.rpm
        
        # 6. Manually trigger the akmod build for evdi.
        # Note: akmods needs to run as root to install the built RPMs.
        # Since we're already running as root in the container build, we can run it directly.
        # The build process runs as root, so akmods can install the built modules.
        RUN akmods --force --kernels $(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -n 1) --akmod evdi

  # Finally, our tuning script to enable the service and set config
  - type: script
    scripts:
      - displaylink-fix.sh
