# This is your custom image name and metadata
name: evilpandas-os
description: My custom Bluefin image with DisplayLink and kernel dev tools.

# This IS Bluefin. Bluefin is part of the ublue-os organization.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  # We consolidate everything into a containerfile module to handle the 
  # complex dependency dance and repo requirements for DisplayLink.
  - type: containerfile
    snippets:
      - |
        # 1. Add the Negativo17 repository
        RUN curl -Lo /etc/yum.repos.d/fedora-multimedia.repo https://negativo17.org/repos/fedora-multimedia.repo
        
        # 2. Install kernel headers and build tools needed for the driver
        RUN rpm-ostree install kernel-devel kernel-headers akmods
        
        # 3. Install the DisplayLink components.
        # Note: rpm-ostree doesn't support --setopt or --assume-yes (those are DNF options).
        # If akmod-evdi gets pulled in as a weak dependency and causes issues,
        # we'll build evdi manually in the next step anyway.
        RUN rpm-ostree install \
            libevdi \
            displaylink
        
        # 4. Manually trigger the akmod build for evdi using the correct parameters
        # for a containerized build environment. This ensures evdi is built correctly
        # even if akmod-evdi was installed or if it needs to be built from source.
        RUN akmods --force --kernels $(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -n 1) --akmod evdi

  # Finally, our tuning script to enable the service and set config
  - type: script
    scripts:
      - displaylink-fix.sh
